# Generated by Django 3.0 on 2020-09-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200916_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
