# Generated by Django 3.0 on 2020-09-21 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200919_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='time',
        ),
        migrations.AddField(
            model_name='workout',
            name='time_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='time_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='time_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
