# Generated by Django 3.0 on 2020-09-21 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200921_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='updated_at',
        ),
    ]
